"""remove the uniqueness of the access token and refresh token and add calendar id column

Revision ID: 156a289814f2
Revises: 468f5e45fb01
Create Date: 2026-07-21 14:22:05.573150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156a289814f2'
down_revision: Union[str, Sequence[str], None] = '468f5e45fb01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_id', sa.String(), nullable=True))
        batch_op.drop_constraint(batch_op.f('users_access_token_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_refresh_token_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('users_refresh_token_key'), ['refresh_token'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_access_token_key'), ['access_token'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('calendar_id')

    # ### end Alembic commands ###
